server:
  port: ${CONFIG_SERVER_PORT:8888}

spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_GIT_URL:https://github.com/lc-ant/config.git}
          username: ${CONFIG_SERVER_GIT_USERNAME}
          password: ${CONFIG_SERVER_GIT_PASSWORD}
      
management:
  endpoints:
    web:
      exposure:
        include: "health,refresh"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
